### ISSUE TITLE
Missing sources: wakelock & network modules

### ISSUE THREAD

**Issue by CathyKMeow** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8350#1]
`drivers/soc/oplus/oplus_wakelock` and `net/oplus_modules` please.

**Comment by OnePlusOSSAdmin** [comment]
drivers/soc/oplus/oplus_wakelock(kernel source tree) -> vendor/oplus/kernel/wakelock_profiler
net/oplus_modules(kernel source tree)  -> vendor/oplus/kernel/network
